version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://pixcoders20_db_user:rFeU4L6mWAQy0AFl@cluster0.so1prz8.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - HOSTNAME=0.0.0.0
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:
  node_modules:

networks:
  app-network:
    driver: bridge